### ISSUE TITLE
Ambilight on/off not reacting

### ISSUE THREAD

**Issue by Denn1992** [athombv/nl.philips.ir#2]
The Ambilight on/off is not being handled by the television.

In the test flow the action card is being executed but nothing happens on the television. The other cards are working fine, so perhaps there is something not configured correctly.

**Comment by kukel** [comment]
for me the ambilight on/off shows (with a substantial delay) the list with ambilight styles (ambilight modus?) and the ambilight modus does nothing for me... Maybe it is tv model related?

**Comment by zperx** [comment]
Ambilight On/Off sometimes works sometimes not. Before this app I have created a IR remote in homey, there I had to use longer IR code to make it work. There should be an option for each command how long to send them (like in the generic IR app)

**Comment by BasKiers** [comment]
Hi,

This could be tv model related. I could look into adding a flow card which will enable you to send multiple repetitions. However this flow card will be limited since app are not able to send a variable amount of repeats so this implementation would be the same as putting multiple "send command" flow cards in the action column without a delay.

Could you try adding multiple of the same "send command" flow card (for instance 3) in the action column and confirm that this fixes the problem?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please open a new issue if you still encounter this issue with the [latest Homey version](https://firmware.athom.com/).

Thank you!
